services:
  - type: web
    name: cayenabot
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
      - path: /*.html
        name: Content-Type
        value: text/html; charset=utf-8
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
